[project]
name = "weather"
version = "0.10"
description = "current weather "
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "mcp>=1.0.0",]

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
weather = "weather:main"
